# Linear Algebra

## Vectors

**A vector is an object that has both a magnitude and a direction.**
![image.png](attachment:image.png)

**Vectors are broadly categorized into:**
- Row Vector
- Column Vector
![image-2.png](attachment:image-2.png)

### Creating and Printing Vector

In [ ]:
# importing numpy
import numpy as np

# creating a 1-D list (Horizontal)
list1 = [1, 2, 3]

# creating a 1-D list (Vertical)
list2 = [[10],
        [20],
        [30]]

# creating a vector1
# vector as row
vector1 = np.array(list1)

# creating a vector 2
# vector as column
vector2 = np.array(list2)

# showing horizontal vector
print("Horizontal Vector")
print(vector1)

print("----------------")

# showing vertical vector
print("Vertical Vector")
print(vector2)

Horizontal Vector
[1 2 3]
----------------
Vertical Vector
[[10]
 [20]
 [30]]


### Arithematic Operations on Vector

In [ ]:
# importing numpy
import numpy as np

# creating a 1-D list (Horizontal)
list1 = [11, 61, 19]

# creating a 1-D list (Horizontal)
list2 = [31, 34, 53]

# creating first vector
vector1 = np.array(list1)

# printing vector1
print("First Vector          : " + str(vector1))

# creating second vector
vector2 = np.array(list2)

# printing vector2
print("Second Vector         : " + str(vector2))

# adding both the vectors
# a + b = (a1 + b1, a2 + b2, a3 + b3)
addition = vector1 + vector2

# printing addition vector
print("Vector Addition       : " + str(addition))

# subtracting both the vectors
# a - b = (a1 - b1, a2 - b2, a3 - b3)
subtraction = vector1 - vector2

# printing subtraction vector
print("Vector Subtraction    : " + str(subtraction))

# multiplying both the vectors
# a * b = (a1 * b1, a2 * b2, a3 * b3)
multiplication = vector1 * vector2

# printing multiplication vector
print("Vector Multiplication : " + str(multiplication))

# dividing both the vectors
# a / b = (a1 / b1, a2 / b2, a3 / b3)
division = vector1 / vector2

# printing division vector
print("Vector Division       : " + str(division))

First Vector          : [11 61 19]
Second Vector         : [31 34 53]
Vector Addition       : [42 95 72]
Vector Subtraction    : [-20  27 -34]
Vector Multiplication : [ 341 2074 1007]
Vector Division       : [0.35483871 1.79411765 0.35849057]


### Dot Product of 2 (1-D) Vectors

**Dot Product**

- Dot product is also known as an inner product.
- To apply the inner product on two vectors, they need to be the **same size.**
- The result of a dot product is a scalar.

For instance, we have two vectors or two ordered vector lists. To apply the dot product, first multiply these ordered vectors element-wise and then sum each product. Let’s have a look at the example.

![dot%20product.webp](attachment:dot%20product.webp)

### Dot product using np.dot()

In [ ]:
# importing numpy
import numpy as np

# creating a 1-D list (Horizontal)
list1 = [2, 7, 1]

# creating a 1-D list (Horizontal)
list2 = [8, 2, 8]

# creating first vector
vector1 = np.array(list1)

# printing vector1
print("First Vector : " + str(vector1))

# creating second vector
vector2 = np.array(list2)

# printing vector2
print("Second Vector : " + str(vector2))

# getting dot product of both the vectors
# a . b = (a1 * b1 + a2 * b2 + a3 * b3)
# a . b = (a1b1 + a2b2 + a3b3) - is another way to represent the equation
dot_product = vector1.dot(vector2)

# Try np.dot(vector1, vector2)

# printing dot product
print("Dot Product : " + str(dot_product))


First Vector : [2 7 1]
Second Vector : [8 2 8]
Dot Product : 38


### Dot product using np.inner() function

In [ ]:
# Alternatively, we can use the np.inner() function.
dot_product = np.inner(vector1, vector2)
print("The dot product of x and y is: ", dot_product)

The dot product of x and y is:  38


### Dot product using an explicit operator @

In [ ]:
# From Python 3.5 we can use an explicit operator @ for the dot product,
# so you can write the following
print("The dot product of vector1 and vector2 is: ", vector1 @ vector2)

The dot product of vector1 and vector2 is:  38


### Scalar Product

In [ ]:
# printing vector1
print("Vector1 : " + str(vector1))

# scalar value
scalar = 2

# printing scalar value
print("Scalar : " + str(scalar))

# getting scalar multiplication value
# s * v = (s * v1, s * v2, s * v3)
scalar_mul = vector1 * scalar

# printing dot product
print("Scalar Multiplication : " + str(scalar_mul))


Vector1 : [2 7 1]
Scalar : 2
Scalar Multiplication : [ 4 14  2]


## Matrix

### Create Matrix using NumPy

In [ ]:
# Creating a Matrix

# Loading library: importing numpy package
import numpy as np

# Create a matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

### Arithematic Operations on Matrix

In [ ]:
# Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

# Add two matrices
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [ ]:
# Alternate way to add two matrices
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [ ]:
# Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

# Subtracting two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [ ]:
# Subtract two matrices
matrix_a - matrix_b

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [ ]:
# Multiply two matrices
np.dot(matrix_a, matrix_b)

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [ ]:
# Multiply two matrices
# Python 3.5+ we can use the @ operator
matrix_a @ matrix_b

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [ ]:
# Multiply two matrices element-wise
matrix_a * matrix_b

array([[ 1,  3,  1],
       [ 1,  3,  1],
       [ 1,  3, 16]])

### numpy.arange
- Values are generated within the half-open interval [start, stop)
- Return evenly spaced values within a given interval.
   
<div class="alert alert-block alert-success">
<b>Syntax</b><br>numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
</div>
   

**Parameters
start: integer or real, optional**
- Start of interval. The interval includes this value. The default start value is 0.

**stop: integer or real**
- End of interval. The interval does not include this value, except in some cases where step is not an integer and floating point round-off effects the length of out.

**step: integer or real, optional**
- Spacing between values. For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. The default step size is 1. If step is specified as a position argument, start must also be given.

**dtype: dtype**
- The type of the output array. If dtype is not given, infer the data type from the other input arguments.

**like: array_like**
- Reference object to allow the creation of arrays that are not NumPy arrays.
- If an array-like passed in as like supports the __array_function__ protocol, the result will be defined by it.
- In this case, it ensures the creation of an array object compatible with that passed in via this argument.


**Returns:  arange: ndarray**
- An Array of evenly spaced values.


In [ ]:
# Create a Matrix using arange() function
matrix2 = np.arange(1, 10) # 10 is not inclusive
matrix2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### numpy.reshape

**It gives a new shape to an array without changing its data.**

<div class="alert alert-block alert-success">
<b>Syntax</b><br>numpy.reshape(a, newshape, order='C')
</div>

**Parameters**
**a**: array_like, Array to be reshaped.

**newshape** : int or tuple of ints
- The new shape should be compatible with the original shape.
- If an integer, then the result will be a 1-D array of that length.
- One shape dimension can be -1. In this case, the value is inferred from the length of the array and remaining dimensions.

**order{‘C’, ‘F’, ‘A’}, optional**
- Read the elements of a using this index order, and place the elements into the reshaped array using this index order.
- ‘C’ means to read/write the elements using C-like index order, with the last axis index changing fastest, back to the first axis index changing slowest.
- ‘F’ means to read/write the elements using Fortran-like index order, with the first index changing fastest, and the last index changing slowest.
- ‘A’ means to read/write the elements in Fortran-like index order, if a is Fortran contiguous in memory, C-like order otherwise.

**Returns**
**reshaped_array** : ndarray

In [ ]:
# Reshape 1-D matrix into 2-D matrix (3 rows and 3 columns)
matrix2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrix2 = matrix2.reshape(3,3)
matrix2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### ndarray.ndim
**Number of array dimensions.**

<div class="alert alert-block alert-success">
<b>Syntax</b><br>ndarray.ndim
</div>
Where

**ndarray**  - is matrix name

In [ ]:
# Print dimension of matrix
matrix2.ndim

2

### ndarray.size
**Number of elements in the array.**

<div class="alert alert-block alert-success">
<b>Syntax</b><br>ndarray.size
</div>

In [ ]:
matrix2.size

9

### numpy.shape
**Return the shape of an array.**

<div class="alert alert-block alert-success">
<b>Syntax</b><br>numpy.shape(a)
</div>


Parameters<br>
**a :** array_like
- Input array.

**Returns: shape:** tuple of ints
- The elements of the shape tuple give the lengths of the corresponding array dimensions.

In [ ]:
matrix2.shape

(3, 3)

### ndarray.max()
**Return the maximum along a given axis**

<div class="alert alert-block alert-success">
<b>Syntax</b><br>ndarray.max(axis=None, out=None, keepdims=False, initial=<no value>, where=True)
</div>

In [ ]:
np.max(matrix2)

np.int64(9)

In [ ]:
# Print maximum element in each column
np.max(matrix2, axis=0)

array([7, 8, 9])

In [ ]:
# Print maximum element in each row
np.max(matrix2, axis=1)

array([3, 6, 9])

### ndarray.min()
**Return the minimum along a given axis**

<div class="alert alert-block alert-success">
<b>Syntax</b><br>ndarray.min(axis=None, out=None, keepdims=False, initial=<no value>, where=True)
</div>
    
![numpy-axis-example_v2.png](attachment:numpy-axis-example_v2.png)

In [ ]:
np.min(matrix2)

np.int64(1)

In [ ]:
# Print minimum element in each column
np.min(matrix2, axis=0)

array([1, 2, 3])

In [ ]:
# Print minimum element in each row
np.min(matrix2, axis=1)

array([1, 4, 7])

### numpy.mean()
**Compute the arithmetic mean along the specified axis.**


**Mean of matrix is =
   (sum of all elements of matrix)/(total elements of matrix)**
   

<div class="alert alert-block alert-success">
<b>Syntax</b><br>numpy.mean(a, axis=None, dtype=None, out=None, keepdims=no value, *, where=no value)
</div>

    
**Parameters**
**a** : array_like.
- Array containing numbers whose mean is desired. If a is not an array, a conversion is attempted.

**axis** : None or int or tuple of ints, optional
- Axis or axes along which the means are computed.
- The default is to compute the mean of the flattened array.
- If this is a tuple of ints, a mean is performed over multiple axes, instead of a single axis or all the axes as before.

**dtype** data-type, optional
- Type to use in computing the mean. For integer inputs, the default is float64; for floating point inputs, it is the same as the input dtype.
    
**out** : ndarray, optional
- Alternate output array in which to place the result. The default is None; if provided, it must have the same shape as the expected output, but the type will be cast if necessary.

**keepdims** : bool, optional
- If this is set to True, the axes which are reduced are left in the result as dimensions with size one. With this option, the result will broadcast correctly against the input array.
    
    
**where** : array_like of bool, optional
- Elements to include in the mean.

**Returns**
**m** : ndarray
- If out=None, returns a new array containing the mean values, otherwise a reference to the output array is returned.

In [ ]:
# Print mean
np.mean(matrix2)

np.float64(5.0)

In [ ]:
# Print mean value in each column
np.mean(matrix2, axis=0)

array([4., 5., 6.])

### numpy.var()
**Returns the variance of the array elements, a measure of the spread of a distribution. The variance is computed for the flattened array by default, otherwise over the specified axis.**


**Mean of matrix is =
   (sum of all elements of matrix)/(total elements of matrix)**
   

<div class="alert alert-block alert-success">
<b>Syntax</b><br>numpy.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=no value, *, where=no value)
</div>

    
**Parameters**
**a** : array_like.
- Array containing numbers whose variance is desired. If a is not an array, a conversion is attempted.

**axis** : None or int or tuple of ints, optional
- Axis or axes along which the variance is computed.
- The default is to compute the variance of the flattened array.
- If this is a tuple of ints, a variance is performed over multiple axes, instead of a single axis or all the axes as before.

**dtype** data-type, optional
- Type to use in computing the variance. For arrays of integer type the default is float64; for arrays of float types it is the same as the array type.
    
**out** : ndarray, optional
- Alternate output array in which to place the result. The default is None. If provided, it must have the same shape as the expected output, but the type will be cast if necessary.
    
**ddof** : int, optional
- **Delta Degrees of Freedom**: the divisor used in the calculation is N. - ddof, where N represents the number of elements. By default ddof is zero.

**keepdims** : bool, optional
- If this is set to True, the axes which are reduced are left in the result as dimensions with size one. With this option, the result will broadcast correctly against the input array.
    
**where** : array_like of bool, optional
- Elements to include in the variance.

**Returns**
**variance** : ndarray
- If out= None, returns a new array containing the variance; otherwise, a reference to the output array is returned.

In [ ]:
# Print variance
np.var(matrix2)

np.float64(6.666666666666667)

### numpy.std()
**Compute the standard deviation along the specified axis.**
- Returns the standard deviation, a measure of the spread of a distribution, of the array elements.
- The standard deviation is computed for the flattened array by default, otherwise over the specified axis.

<div class="alert alert-block alert-success">
<b>Syntax</b><br>numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=no value, *, where=no value)
</div>
    
**Parameters**
**a** : array_like.
- Calculate the standard deviation of these values.

**axis** : None or int or tuple of ints, optional
- Axis or axes along which the standard deviation is computed.
- The default is to compute the standard deviation of the flattened array.
- If this is a tuple of ints, a variance is performed over multiple axes, instead of a single axis or all the axes as before.

**dtype** data-type, optional
- Type to use in computing the standard deviation. For arrays of integer type the default is float64, for arrays of float types it is the same as the array type.
    
**out** : ndarray, optional
- Alternative output array in which to place the result.
- It must have the same shape as the expected output but the type (of the calculated values) will be cast if necessary.
    
**ddof** : int, optional
- **Delta Degrees of Freedom** : the divisor used in the calculation is N - ddof, where N represents the number of elements. By default ddof is zero.

**keepdims** : bool, optional
- If this is set to True, the axes which are reduced are left in the result as dimensions with size one. With this option, the result will broadcast correctly against the input array.
    
**where** : array_like of bool, optional
- Elements to include in the standard deviation.

**Returns**
**standard_deviation** : ndarray
- If out is None, return a new array containing the standard deviation, otherwise return a reference to the output array.

In [ ]:
# Print standard deviation
np.std(matrix2)

np.float64(2.581988897471611)

### ndarray.T
**The transposed array.**

In [ ]:
# Transpose a matrix
matrix2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
mTest = [[2, 3], [4, 8]]
print(mTest)
np.linalg.inv(mTest)

[[2, 3], [4, 8]]


array([[ 2.  , -0.75],
       [-1.  ,  0.5 ]])

In [ ]:
# Inverse a matrix
np.linalg.inv(matrix2)

LinAlgError: Singular matrix

To make `matrix2` invertible, we need to modify its values so that its rows (or columns) are no longer linearly dependent. Let's change one element to achieve this and then verify its invertibility.

In [ ]:
# Modifying matrix2 to be invertible
matrix2_invertible = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 10] # Changed 9 to 10 to break linear dependency
])

print("New invertible matrix2:")
print(matrix2_invertible)

New invertible matrix2:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


In [ ]:
# Calculate the inverse of the new matrix2
inverse_matrix2 = np.linalg.inv(matrix2_invertible)

print("\nInverse of the new matrix2:")
print(inverse_matrix2)


Inverse of the new matrix2:
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


As you can see, by changing one element, the `LinAlgError` is resolved, and the inverse matrix is successfully computed. This is because the modified matrix is no longer singular.

In [ ]:
# Flatten matrix - to transform a matrix into a one-dimensional array
matrix2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### numpy.linalg.matrix_rank
**Return matrix rank of array using SVD method**
- Rank of the array is the number of singular values of the array that are greater than tol.

<div class="alert alert-block alert-success">
<b>Syntax</b><br>linalg.matrix_rank(M, tol=None, hermitian=False)
</div>
    
**Parameters**
**M** : {(M,), (…, M, N)} array_like
- Input vector or stack of matrices.


**tol** : (…) array_like, float, optional
- Threshold below which SVD values are considered zero.
- If tol is None, and S is an array with singular values for M, and eps is the epsilon value for datatype of S, then tol is set to S.max() * max(M.shape) * eps.

**Returns** : **rank** : (…) array_like
- Rank of M

![rank.svg](attachment:rank.svg)

In [ ]:
# Print rank of matrix
np.linalg.matrix_rank(matrix2)

np.int64(2)

In [ ]:
matrix2 = matrix2.reshape(3,3)
matrix2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Print determinant of matrix
np.linalg.det(matrix2)

np.float64(0.0)

In [ ]:
# Print diagonal elements
matrix2.diagonal()

array([1, 5, 9])

### numpy.linalg.eig
- Compute the eigen values and right eigen vectors of a square array.

<div class="alert alert-block alert-success">
<b>Syntax</b><br>linalg.eig(a)
</div>
    
**Parameters**
**a** : (…, M, M) array
- Matrices for which the eigen values and right eigen vectors will be computed.

**Returns**

**w** : (…, M) array
- The eigen values are each repeated according to its multiplicity. The eigen values are not necessarily ordered.

**v** : (…, M, M) array
- The normalized (unit “length”) eigen vectors, such that the column v[:,i] is the eigen vector corresponding to the eigen value w[i].

![eigenvalue_eigenvector.png](attachment:eigenvalue_eigenvector.png)

In [ ]:
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix2)

In [ ]:
# Print eigenvalues
eigenvalues

array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15])

In [ ]:
# Print eigenvectors
eigenvectors

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])

### Tasks

In [ ]:
# Create a matrix of even numbers
matrix3 = np.arange(0,11,2)
matrix3 = matrix3.reshape(2,3)
matrix3

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [ ]:
# Aim: Create a matrix of Odd Numbers from 0 to 12 (modified to 0 to 18 to allow a 3x3 square matrix)

# Create a matrix using arange()
matrix3_elements = np.arange(1, 18, 2) # Generates 1, 3, 5, 7, 9, 11, 13, 15, 17 (9 elements)

# Reshape 1-D matrix into 2-D matrix (3x3)
matrix3 = matrix3_elements.reshape(3,3)

# Modify one element to make it invertible
matrix3[2,2] = 18 # Changed 17 to 18 to break linear dependency
matrix3

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 18]])

In [ ]:
# Print number of elements in matrix3 (rows * columns)
print("Number of elements in matrix3:", matrix3.size)

Number of elements in matrix3: 9


In [ ]:
# Print number of rows and columns in matrix3
print("Shape of matrix3 (rows, columns):", matrix3.shape)

Shape of matrix3 (rows, columns): (3, 3)


In [ ]:
# Print maximum element in matrix3

In [ ]:
# Print minimum element in matrix3

In [ ]:
# Print maximum element in each column of matrix3

In [ ]:
# Print maximum element in each row of matrix3

In [ ]:
# Print Transpose of matrix 3

In [ ]:
# Print Inverse of matrix3
print("Inverse of matrix3:\n", np.linalg.inv(matrix3))

Inverse of matrix3:
 [[ 0.25       -1.75        1.        ]
 [-1.41666667  3.91666667 -2.        ]
 [ 1.         -2.          1.        ]]


In [ ]:
# Print rank of matrix3
print("Rank of matrix3:", np.linalg.matrix_rank(matrix3))

Rank of matrix3: 3


In [ ]:
# Print determinant of matrix3

In [ ]:
# Print diagonal elements of matrix3

In [ ]:
# Print eigenvalues and eigenvectors of matrix3

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
